pipeline:
  build:
    image: python:3.5-alpine
    commands:
      - pip install --no-cache-dir --upgrade pip setuptools wheel flake8
      - flake8 run_devpi.py
      - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
      - pip install --use-wheel --no-index --find-links=wheeldir -r requirements.txt
      - python test.py


  publish:
    image: plugins/docker
    username: ${DOCKER_USER}
    password: ${DOCKER_PASS}
    email: ${DOCKER_EMAIL}
    repo: plugins/drone-devpi
    when:
      branch: master


services:
  devpi:
    image: muccg/devpi:latest